{
 "title": "DATAPROJECT2-ONPREMISE",
 "time": { "from": "now-4h", "to": "now+1h" },
 "refresh": "5s",
 "panels": [
  {
   "title": "ACUTAL POWER PER PANEL ID",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "app_db",
     "rawSql": "SELECT time_data, power_panel, Panel_id FROM app_db.panelData LIMIT 5000000 "
    }
   ]
  },
  {
   "title": "TOTAL POWER GENERATED",
   "type": "stat",
   "gridPos": { "h": 2, "w": 13, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "app_db",
     "rawSql": "SELECT window_end, total_power, Panel_id FROM app_db.panelDataAgg LIMIT 500000 "
    }
   ]
  },
  {
   "title": "ACTUAL STATUS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 11, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "app_db",
     "rawSql": "SELECT time_data, current_status, Panel_id FROM app_db.panelData LIMIT 500000 "
    }
   ]
  },
  {
   "title": "ACTUAL TOTAL POWER",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "app_db",
     "rawSql": "SELECT window_end, total_power, Panel_id FROM app_db.panelDataAgg LIMIT 500000 "
    }
   ]
  },
  {
   "title": "POWER GENERATION DISTRIBUTION",
   "type": "histogram",
   "gridPos": { "h": 12, "w": 13, "x": 11, "y": 8 },
   "targets": [
    {
     "dataset": "app_db",
     "rawSql": "SELECT window_end, total_power, Panel_id FROM app_db.panelDataAgg LIMIT 50000000 "
    }
   ]
  },
  {
   "title": "ACTUAL TOTAL POWER",
   "type": "graph",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dataset": "app_db",
     "rawSql": "SELECT window_end, total_power, Panel_id FROM app_db.panelDataAgg LIMIT 500000 "
    }
   ]
  }
 ]
}